# Generated by Django 4.2.7 on 2023-11-14 10:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.TextField()),
                ('PhoneNumber', models.TextField()),
                ('RoomNumber', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(701), django.core.validators.MaxValueValidator(710)])),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('PositionID', models.AutoField(primary_key=True, serialize=False)),
                ('PositionName', models.TextField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BonusPercentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectNumber', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.TextField()),
                ('Deadline', models.DateField()),
                ('Funding', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExecution',
            fields=[
                ('ExecutionID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departments')),
                ('ProjectNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('LastName', models.TextField()),
                ('FirstName', models.TextField()),
                ('MiddleName', models.TextField()),
                ('Address', models.TextField()),
                ('Phone', models.TextField()),
                ('Education', models.CharField(choices=[('спеціальна', 'спеціальна'), ('середня', 'середня'), ('вища', 'вища')], max_length=20)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departments')),
                ('PositionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.positions')),
            ],
        ),
    ]
